### ISSUE TITLE
build script lacks execution permission

### ISSUE THREAD

**Issue by TelephoneTan** [dokar3/quickjs-kt#100]
`./quickjs/native/cmake/zig-ar.sh`
`./quickjs/native/cmake/zig-ranlib.sh`

**Comment by dokar3** [comment]
You might need to grant execute permission manually, see: 
https://github.com/dokar3/quickjs-kt/blob/f748724d8d25c282d19e4d455372144def92f80c/.github/workflows/build.yaml#L56

**Comment by dokar3** [comment]
Didn't even know this existed. As a Windows user, it feels somewhat illegal.

**Comment by TelephoneTan** [comment]
After `chmod`, `git status` will show that the files have been modified.

**Comment by dokar3** [comment]
Good, I just searched it, this requires `configs core.filemode true`, will try on WSL later if it works.
