### ISSUE TITLE
suspend functions 

### ISSUE THREAD

**Issue by dgmltn** [dokar3/quickjs-kt#8]
Have you tried to use a suspend function via reflection, as shown below? I'm getting an error "parameter count mismatched"

```
class Http {
    suspend fun fetch(url: String) = "..."
}

quickJs {
    define<Http>("http", Http())

    evaluate<Any?>(
        """
        await http.fetch("https://www.example.com")
        """.trimIndent()
    )
}
```

**Comment by dokar3** [comment]
Currently, reflection bindings do not support suspend functions. You can delegate that instance to a DSL binding.

**Comment by dgmltn** [comment]
Ok, thanks!

**Comment by dokar3** [comment]
Done in #27
