### ISSUE TITLE
2 files found with path 'lib/arm64-v8a/libquickjs.so' from inputs:

### ISSUE THREAD

**Issue by TelephoneTan** [dokar3/quickjs-kt#99]
I try to run my project on my Android phone, but it fails with error:
```
2 files found with path 'lib/arm64-v8a/libquickjs.so' from inputs:
 - C:\Users\Terry\.gradle\caches\8.8\transforms\d815028faf901d4d4975b34335a30e4f\transformed\quickjs-release\jni\arm64-v8a\libquickjs.so
 - C:\Users\Terry\.gradle\caches\8.8\transforms\c5c5b7415d5b142347150f6c559b9ab3\transformed\zipline-release\jni\arm64-v8a\libquickjs.so
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

**Comment by dokar3** [comment]
Yes, It uses the same name 'libquickjs' as Zipline, so it's incompatible with Zipline, this can't be avoided IMO.

If there is a solution please let me know.

**Comment by TelephoneTan** [comment]
I clear all built caches, and it works now. 

I have been using ZiplineJS in my project until I can't stand its weird StackOverflow exceptions anymore. ZiplineJS has few documents, and it doesn't support Windows as well.

So I am on this library now.

**Comment by dokar3** [comment]
I see, Zipline is great and it inspired this library, but I can't set it up without Kotlin/JS, so I gave it up😥.
